defaults: &defaults
  docker:
    - image: 20scoops/ruby-cypress
      environment:
        TERM: xterm
  working_directory: ~/app
  parallelism: 1

version: 2
jobs:
  install_and_checking:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache/Cypress
      - run:
          name: Check Prettier Code
          command: yarn prettier:check
      - restore_cache:
          name: Restore Cache Gems
          keys:
            - v3-gems-{{ checksum "Gemfile.lock" }}
            - v3-gems-
      - run:
          name: Bundle Install
          command: |
            bundle install --path vendor/bundle
      - save_cache:
          name: Save Cache Gems
          key: v3-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - run:
          name: Run Danger
          command: bundle exec danger
  E2E_Testing:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - attach_workspace:
          at: ~/
      - run:
          name: Example Testing
          command:
            yarn e2e_mochawesome
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: mochawesome-report
workflows:
  version: 2
  'Cypress Workflow':
    jobs:
      - install_and_checking:
          filters:
            branches:
              only:
                - dev
      - E2E_Testing:
          requires:
            - install_and_checking
  working_on_schedule:
    triggers:
      - schedule:
          cron: '0 12 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - install_and_checking
      - E2E_Testing:
          requires:
            - install_and_checking

