version: 2.1

orbs:
    cypress: cypress-io/cypress@1

workflows:
    "Cypress Workflow":
        jobs:
          - cypress/install
          - cypress/run:
                name: Test 1
                requires:
                    - cypress/install
                command: npm run e2e_mochawesome
                post-steps:
                    - store_artifacts:
                        path: cypress/videos
                    - store_artifacts:
                        path: mochawesome-report
          - cypress/run:
                name: Test 2
                requires:
                    - cypress/install
                command: npm run e2e_mochawesome
                post-steps:
                    - store_artifacts:
                        path: cypress/videos
                    - store_artifacts:
                        path: mochawesome-report
