version: 2.1

orbs:
    cypress: cypress-io/cypress@1

workflows:
    "Cypress Workflow":
        jobs:
          - cypress/install
          - cypress/run:
                name: Test 1
                requires:
                    - cypress/install
                command: npx cypress run --spec "cypress/integration/examples/aliasing.spec.js"
                post-steps:
                    - store_artifacts:
                        path: cypress/videos
                    - store_artifacts:
                        path: cypress/screenshots

          - cypress/run:
                name: Test 2
                requires:
                    - cypress/install
                command: npx cypress run --spec "cypress/integration/examples/assertions.spec.js"
                post-steps:
                    - store_artifacts:
                        path: cypress/videos
                    - store_artifacts:
                        path: cypress/screenshots